Write a new classifier and refactor the entire assignment (#57)
* Counting of words is working properly

* training and testing data is stored in ram

* Fixed performance issue
- Summerizing all values in huge dictionaries takes a while if you do it all the time.

* Fixed bug
- AttributeError: 'list' object has no attribute 'get', were using a list of reviews and not the dictionary with the counted words.

* Solved the log issue

* Moved functions in to data_handler

* Accuracy is measured when predicting the test reviews

* Refactored testing and cli
- Removed a lot of old tests

* Using count_text everywhere now instead of the one I made.
- make_word_frequency_dict() removed

* Saving the trained classifier to the drive and attempt to load that file when using the classifier

* All files created by the program can be deleted

* Stopwords have returned and increases accuracy by 1% yeee

* Added the ability to see the most common words

* More refactoring

* Added ability to see most common words in training data

* Improved cli experience
- Removed old commands

* predictor is now known as classifier

* The predictions are timed

* Changed the name of the saved test data

* Added some feedback to invalid input